/*CHECKS*/
ALTER TABLE PRODUCCION_LOTE DROP CONSTRAINT CH_PL_TIPO;
ALTER TABLE ESTADO_CIUDAD DROP CONSTRAINT CH_EC_TIPO;
ALTER TABLE INSTALACION DROP CONSTRAINT CH_INS_TIPO;
ALTER TABLE CLASIFICACION DROP CONSTRAINT CH_CL_TIPO;
ALTER TABLE CLIENTE_VISITANTE DROP CONSTRAINT CH_CV_GENERO;
ALTER TABLE CLIENTE_VISITANTE DROP CONSTRAINT CH_CV_EXPERIENCIA;
ALTER TABLE CLIENTE_VISITANTE DROP CONSTRAINT CH_CV_TIPOCLIENTE;
ALTER TABLE VALORACION DROP CONSTRAINT CH_VA_EXPERIENCIA;
ALTER TABLE VALORACION DROP CONSTRAINT CH_VA_CALIDAD_PR; 
ALTER TABLE VALORACION DROP CONSTRAINT CH_VA_DIFICULTAD; 

/*UNIQUE*/
ALTER TABLE CLASIFICACION DROP CONSTRAINT UN_CL_NOMBRE;
ALTER TABLE PAIS DROP CONSTRAINT UN_PA_NOMBRE;
ALTER TABLE PAIS DROP CONSTRAINT UN_PA_NACIONALIDAD;
ALTER TABLE PRODUCTO DROP CONSTRAINT UN_PR_NOMBRE;