create or replace PROCEDURE AGREGA_PRODUCTO( 
TIENDA PEDIDO.PD_FK_TIENDA%TYPE, LEGO DETALLE_PEDIDO.DIP_FK_PRODUCTO%TYPE, FABRICA PEDIDO.PD_FK_FABRICA%TYPE, CANT DET_LOTE.DL_CANTIDAD%TYPE ) IS

ID_PAIS NUMBER(7);
ID_PEDIDO NUMBER(7);
PRODUCTO_DISPONIBLE NUMBER(7):=NULL;
ID_DETALLE NUMBER (7);
CUENTA NUMBER(3);
APUN NUMBER(3);
ID_INCREMENTO NUMBER(7):=0;
P_LOTE NUMBER(7);
CANTIDAD_LOTE NUMBER(7);
MODULO NUMBER(7);

BEGIN
-- devuelve el pais de la fabrica
SELECT DIP_FK_PAIS INTO ID_PAIS 
FROM DISP_PROD 
WHERE DIP_FK_PAIS = (SELECT PA_ID FROM PAIS, ESTADO_CIUDAD, FABRICA WHERE EC_ID = FA_FK_CIUDAD 
AND FA_ID = FABRICA AND EC_FK_PAIS = PA_ID);

--toma el ultimo insert de pedido
SELECT PD_ORDEN INTO ID_PEDIDO FROM PEDIDO WHERE ROWNUM = 1 ORDER BY PD_ORDEN DESC;


--toma id del pais en DISP_PROD, comparando disponibilidad del producto por pais
SELECT DIP_FK_PAIS INTO PRODUCTO_DISPONIBLE FROM DISP_PROD WHERE DIP_FK_PAIS=ID_PAIS AND DIP_FK_PRODUCTO= LEGO;


--si la busqueda no retorna un null hace la insercion en detalle pedido
IF PRODUCTO_DISPONIBLE = NULL THEN 
DBMS_OUTPUT.PUT_LINE('EL PRODUCTO NO SE ENCUENTRA DISPONIBLE PARA ESE PAIS');
ELSE
     INSERT INTO DETALLE_PEDIDO VALUES (SQ_DETALLE_PEDIDO_ID.NEXTVAL,ID_PEDIDO,ID_PAIS,LEGO,0,0);
    --TOMA EL LOTE DEL PRODUCTO EN EL HISTORICO / OJO ESTE TIENE QUE ESTAR CONDICIONADO POR LOS DESCUENTOS
     SELECT PL_ID_LOTE INTO P_LOTE FROM PRODUCCION_LOTE WHERE PL_FK_HIST_FABRICA=FABRICA AND PL_FK_HIST_PRODUCTO = LEGO AND ROWNUM = 1;
     --TOMA EL ULTIMO DETALLE O PRODUCTO 
     SELECT DP_ID INTO ID_DETALLE FROM DETALLE_PEDIDO, PEDIDO WHERE DP_FK_PEDIDO = PD_ORDEN AND PD_ORDEN = ID_PEDIDO AND ROWNUM = 1 ORDER BY DP_ID DESC  ;
     
    
  /*
     SELECT DP_ID INTO ID_DETALLE 
     FROM DETALLE_PEDIDO, DET_LOTE 
     WHERE DP_FK_PEDIDO = ID_PEDIDO AND DP_ID <> DL_FK_DET_PEDIDO AND DL_FK_PEDIDO <> DP_FK_PEDIDO; 
    */
     --SELECT COUNT(*) INTO CUENTA FROM PRODUCCION_LOTE WHERE PL_FK_HIST_FABRICA=FABRICA AND PL_FK_HIST_PRODUCTO = LEGO;
     
     
     --MODULO := CANTIDAD_LOTE - CANT;
    

     INSERT INTO DET_LOTE VALUES (P_LOTE,ID_PEDIDO,ID_DETALLE,CANT);
     
     
end if;

END;