create or replace PROCEDURE realizar_pedido(TIENDA PEDIDO.PD_FK_TIENDA%TYPE, FABRICA PEDIDO.PD_FK_FABRICA%TYPE , 
FEC_PEDIDO PEDIDO.PD_FEC_PEDIDO%TYPE, FEC_OBJETIVO PEDIDO.PD_FEC_OBJETIVO%TYPE) IS

ID_PEDIDO NUMBER (7);
ID_PAIS NUMBER(7);
INICIO NUMBER (3);
PRODUCTO_DISPONIBLE NUMBER(7);

BEGIN 
insert into PEDIDO values 
(TIENDA,FABRICA,
SQ_PEDIDO_ID.nextval,SQ_PEDIDO_NUMERO_ID.NEXTVAL,FEC_PEDIDO,FEC_OBJETIVO,NULL,NULL);

END realizar_pedido;