--ESTA FUNCION REGISTRA UN PEDIDO CON UN PRODUCTO , NO DESUENTA DEL LOTE

create or replace PROCEDURE realizar_pedido(TIENDA PEDIDO.PD_FK_TIENDA%TYPE, FABRICA PEDIDO.PD_FK_FABRICA%TYPE , 
FEC_PEDIDO PEDIDO.PD_FEC_PEDIDO%TYPE, FEC_OBJETIVO PEDIDO.PD_FEC_OBJETIVO%TYPE, LEGO PRODUCTO.PR_CODIGO%TYPE) IS
ID_PEDIDO NUMBER (7);
ID_DISPONIBILIDAD NUMBER(7);
INICIO NUMBER (3);
PRODUCTO_DISPONIBLE NUMBER(7):= NULL;

BEGIN 
insert into PEDIDO values 
(TIENDA,FABRICA,
SQ_PEDIDO_ID.nextval,SQ_PEDIDO_NUMERO_ID.NEXTVAL,FEC_PEDIDO,FEC_OBJETIVO,NULL,NULL);


-- devuelve el pais de la fabrica
SELECT DIP_FK_PAIS INTO ID_DISPONIBILIDAD 
FROM DISP_PROD 
WHERE DIP_FK_PAIS = (SELECT PA_ID FROM PAIS, ESTADO_CIUDAD, FABRICA 
WHERE EC_ID = FA_FK_CIUDAD AND FA_ID = FABRICA AND EC_FK_PAIS = PA_ID);

--toma el ultimo insert de pedido
SELECT PD_ORDEN INTO ID_PEDIDO FROM PEDIDO WHERE ROWNUM < 1 ORDER BY PD_ORDEN DESC;
--toma id del pais en DISP_PROD, comparando disponibilidad del producto por pais
SELECT DIP_FK_PAIS INTO PRODUCTO_DISPONIBLE FROM DISP_PROD WHERE DIP_FK_PAIS=ID_DISPONIBILIDAD AND DIP_FK_PRODUCTO= LEGO;


--si la busqueda no retorna un null hace la insercion en detalle pedido

IF PRODUCTO_DISPONIBLE = NULL THEN 
DBMS_OUTPUT.PUT_LINE('EL PRODUCTO NO SE ENCUENTRA DISPONIBLE PARA ESE PAIS');
ELSE
INSERT INTO DETALLE_PEDIDO VALUES (SQ_DETALLE_PEDIDO_ID.NEXTVAL,ID_PEDIDO,PRODUCTO_DISPONIBLE,LEGO,0,0);
END IF; 

END realizar_pedido;