--CLASIFICACION
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'SPEED CHAMPIONS','JUEGA CON EL NUEVO SET DE CARRERA','N','TEMA',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'STAR WARS','JUEGA CON EL NUEVO SET DE STAR WARS INSPIRADOS EL LA SAGA','S','TEMA',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'THE CLONE WARS','INSPIRADA EN LAS PELICULAS DE STAR WARS','S','SUBTEMA',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'REBELS','INSPIRADA EN LAS PELICULAS DE STAR WARS','S','SUBTEMA',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'ANGRY BIRDS','INSPIRADA EN EL FAMOSO JUEGO QUE HA ARRAZADO GOOGLE PLAY','S','TEMA',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'NINJAGO','MAESTROS DEL SPINJITZU','S','SERIE',NULL);
insert into clasificacion values (SQ_CLASIFICACION_ID.NEXTVAL,'SKY SHARK','MAESTROS DEL SPINJITZU','S','SUBTEMA',NULL);

--CLAS_CLAS
INSERT INTO CLAS_CLAS VALUES ((SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'STAR WARS'),(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'THE CLONE WARS'));
INSERT INTO CLAS_CLAS VALUES ((SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'STAR WARS'),(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'REBELS'));
INSERT INTO CLAS_CLAS VALUES ((SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'SKY SHARK'));


--CLIENTE_VISITANTE
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  7,  6,'KYRA'		,NULL,'FOLEY'		,NULL,TO_DATE('02-Jul-69','DD-MON-RR'),'M','E','P',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 19,  9,'DOLAN'		,NULL,'BYERS'		,NULL,TO_DATE('05-Mar-52','DD-MON-RR'),'H','I','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  8,  3,'KELSIE'		,NULL,'ENGLAND'		,NULL,TO_DATE('20-Oct-79','DD-MON-RR'),'M','I','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 19,  7,'COLE'		,NULL,'LINDSEY'		,NULL,TO_DATE('25-Nov-55','DD-MON-RR'),'H','I','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  9,  5,'KASPER'		,NULL,'ROBERTSON'	,NULL,TO_DATE('12-Feb-71','DD-MON-RR'),'H','I','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 16,  2,'PATRICK'	,NULL,'PETERS'		,NULL,TO_DATE('18-Feb-76','DD-MON-RR'),'H','E','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 10,  5,'VIOLET'		,NULL,'CAREY'		,NULL,TO_DATE('27-Oct-81','DD-MON-RR'),'M','I','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 12,  6,'RAYMOND'	,NULL,'ZIMMERMAN'	,NULL,TO_DATE('28-Apr-54','DD-MON-RR'),'H','A','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 11,  1,'NAYDA'		,NULL,'GRANT'		,NULL,TO_DATE('08-May-84','DD-MON-RR'),'M','I','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  2,  2,'GRADY'		,NULL,'HESTER'		,NULL,TO_DATE('02-Jul-78','DD-MON-RR'),'M','E','O',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 11,  8,'PATIENCE'	,NULL,'LEVINE'		,NULL,TO_DATE('19-Feb-80','DD-MON-RR'),'M','E','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 20,  5,'GRACE'		,NULL,'FITZPATRICK'	,NULL,TO_DATE('11-Mar-70','DD-MON-RR'),'M','E','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 10,  8,'APRIL'		,NULL,'HAMPTON'		,NULL,TO_DATE('01-Apr-71','DD-MON-RR'),'M','E','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 11,  8,'KARINA'		,NULL,'LINDSEY'		,NULL,TO_DATE('23-Apr-69','DD-MON-RR'),'M','E','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  3,  7,'FRANCIS'	,NULL,'MCGEE'		,NULL,TO_DATE('20-Feb-89','DD-MON-RR'),'H','I','O',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  1,  2,'CHARITY'	,NULL,'PAGE'		,NULL,TO_DATE('05-Dec-73','DD-MON-RR'),'M','N','P',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  2,  7,'YARDLEY'	,NULL,'HENDERSON'	,NULL,TO_DATE('28-Mar-77','DD-MON-RR'),'M','E','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  6,  1,'AKEEM'		,NULL,'SHORT'		,NULL,TO_DATE('24-Jul-84','DD-MON-RR'),'M','N','O',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  9,  1,'FAITH'		,NULL,'CASEY'		,NULL,TO_DATE('08-May-67','DD-MON-RR'),'M','I','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  2,  7,'KAY'		,NULL,'PACE'		,NULL,TO_DATE('22-Mar-81','DD-MON-RR'),'H','E','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 17,  1,'RASHAD'		,NULL,'FRANCIS'		,NULL,TO_DATE('08-Oct-77','DD-MON-RR'),'H','N','O',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  9,  8,'COOPER'		,NULL,'DUKE'		,NULL,TO_DATE('13-Jan-69','DD-MON-RR'),'H','I','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  4,  3,'BORIS'		,NULL,'RICHARDSON'	,NULL,TO_DATE('02-Jun-83','DD-MON-RR'),'H','E','O',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 12,  5,'VINCENT'	,NULL,'ELLISON'		,NULL,TO_DATE('13-Jan-58','DD-MON-RR'),'H','A','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  1,  4,'UPTON'		,NULL,'WATKINS'		,NULL,TO_DATE('02-Jul-56','DD-MON-RR'),'H','E','P',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 11,  6,'KATELYN'	,NULL,'ANDREWS'		,NULL,TO_DATE('24-Mar-51','DD-MON-RR'),'M','I','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 19,  5,'JOSEPHINE'	,NULL,'GLENN'		,NULL,TO_DATE('16-Feb-61','DD-MON-RR'),'M','A','D',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL, 15,  9,'BERNARD'	,NULL,'JONES'		,NULL,TO_DATE('22-Jun-76','DD-MON-RR'),'H','A','F',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  6,  7,'JOLIE'		,NULL,'NEWMAN'		,NULL,TO_DATE('14-Oct-80','DD-MON-RR'),'M','A','A',NULL);
INSERT INTO CLIENTE_VISITANTE VALUES (SQ_CLIENTE_VISITANTE_ID.NEXTVAL,NULL,  2,  1,'HAYFA'		,NULL,'LUCAS'		,NULL,TO_DATE('18-Sep-52','DD-MON-RR'),'H','I','P',NULL);

--FACTURA ONLINE
INSERT INTO FACTURA_ONLINE VALUES (SQ_FACTURA_ONLINE_ID.NEXTVAL,(select cv_id from cliente_visitante where rownum = 1)+1,TO_DATE('13-ene-98','DD-MOM-RR'),23.4);
INSERT INTO FACTURA_ONLINE VALUES (SQ_FACTURA_ONLINE_ID.NEXTVAL,(select cv_id from cliente_visitante where rownum = 1)+2,TO_DATE('16-ene-98','DD-MOM-RR'),13.4);
INSERT INTO FACTURA_ONLINE VALUES (SQ_FACTURA_ONLINE_ID.NEXTVAL,(select cv_id from cliente_visitante where rownum = 1)+3,TO_DATE('20-ene-98','DD-MOM-RR'),26.4);
INSERT INTO FACTURA_ONLINE VALUES (SQ_FACTURA_ONLINE_ID.NEXTVAL,(select cv_id from cliente_visitante where rownum = 1)+4,TO_DATE('29-ene-98','DD-MOM-RR'),23.4);
INSERT INTO FACTURA_ONLINE VALUES (SQ_FACTURA_ONLINE_ID.NEXTVAL,(select cv_id from cliente_visitante where rownum = 1)+5,TO_DATE('09-ene-98','DD-MOM-RR'),43.4);