INSERT INTO PRODUCTO VALUES(5005117,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Minifigura despertador de Jay','Deja que la Minifigura Despertador de Jay de LEGO® NINJAGO™ te proteja mientras duermes, y despiertes listo para tus aventuras diarias. Mira la hora en la pantalla LCD fácil de leer, mueve los brazos, muñecas y piernas de la minifigura jumbo de Jay y presiona su cabeza para activar el silenciador y la luz de fondo. El regalo ideal para los fans de sets LEGO NINJAGO.',RANGOS_VA(RANGO(6,99)),29.99,1,RESUMEN(23,12,9,IDIOMAS_VA('INGLES','ESPAÑOL'),'Levántate para las batallas ninja con esta Minifigura Despertador de Jay que incluye una minifigura jumbo movible, pantalla LCD, y funciones de silenciar y luz de fondo.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_5005117_1.png'))),TO_DATE('19-MAY-16','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('NUEVOS','MINIFIGURAS'));
INSERT INTO PRODUCTO VALUES(70751,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Templo de Airjitzu','¡Disfruta de la experiencia de construcción LEGO® NINJAGO™ definitiva con el majestuoso Templo de Airjitzu y el poblado de alrededor! El asombroso templo posee numerosos detalles arquitectónicos. La elaborada estructura de las paredes de la herrería cercana y los suaves tejados en curva del mercado de contrabando pondrán también a prueba tus habilidades de construcción con LEGO. ¡Apaga entonces las luces de tu habitación para ver el teatro de sombras giratorio en el templo!

***Incluye 12 minifiguras con diferentes armas: Lloyd, Kai, Jay, Zane, Cole, Nya, Wu, Misako, Dareth, cartero, Jesper y Claire.
***Armas incluidas: katanas para Lloyd, Kai, Jay, Zane, Cole y Nya.
***¡Busca los cofres escondidos en el mercado de contrabando!
***¡Prepara un espectáculo para tus amigos con el teatro de sombras giratorio!
***Recrea tus escenas favoritas de la serie de televisión NINJAGO™: Maestros del Spinjitzu.',RANGOS_VA(RANGO(14,99)),199.99,2028,RESUMEN(42,52,35,IDIOMAS_VA('INGLES','ESPAÑOL','FRANCÉS'),'¡Construye el majestuoso Templo de Airjitzu! Cuenta con teatro de sombras giratorio con ladrillo luminoso, herrería y mercado de contrabando.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_70751_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_70751_2.png'))),TO_DATE('02-SEP-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('DIFICILES DE ENCONTRAR','EDIFICIOS','EXCLUSIVOS'));
INSERT INTO PRODUCTO VALUES(851345,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Tapete de juego','¡Pon en marcha las aventuras más emocionantes con el Tapete de juego LEGO® NINJAGO™! Este tapete de cartón plastificado impreso a doble cara cuenta con diferentes paisajes inspirados en el mundo de NINJAGO por cada lado. ¡Reúne tus sets LEGO NINJAGO favoritos y prepárate para escenificar asombrosas batallas!

***Tapete de juego de cartón plastificado impreso a doble cara con diferentes paisajes inspirados en el mundo de NINJAGO™ por cada lado.
***¡Planifica tu propia ruta a través de NINJAGO™!
***Combínalo con los sets LEGO® NINJAGO™ para disfrutar de aún más opciones de juego.',RANGOS_VA(RANGO(6,99)),7.48,1,RESUMEN(100,63,1,IDIOMAS_VA('INGLES','ESPAÑOL'),'¡Sumérgete en una aventura ninja con el Tapete de juego LEGO® NINJAGO™! Plastificado e impreso a doble cara, cuenta con asombrosos paisajes inspirados en el mundo de NINJAGO.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_851345_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_851345_2.png'))),TO_DATE('01-JUN-12','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('HOME'));
INSERT INTO PRODUCTO VALUES(70756,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Entrenamiento en el Dojo','Participa con Kai en un emocionante Enfrentamiento en el Dojo, como parte del Torneo de los Elementos. Demuestra tu velocidad y agilidad al esquivar al peligroso robot y sus espadas giratorias escalando la pared como un experto. Lucha contra Griffin Turner y Karlof mientras esquivas las demoledoras manos gigantes de Karlof y te apoderas de la Espada de Jade. Asegúrate de no caer por la trampilla a la prisión de fuego, ¡porque no podrás salir jamás! Incluye 4 minifiguras con armas: Kai, Sleven, Griffin Turner y Karlof.

***Armas incluidas: hoz de Kai, hoz de Sleven y bastón bo de Griffin Turner.
***Pon a prueba tu agilidad con el robot y sus espadas giratorias.
***Esquiva los dardos con punta envenenada.
***Sube por los escalones o la cadena para llegar a lo más alto del dojo.
***Esquiva las demoledoras manos de Karlof.
***¡No caigas por la trampilla en la prisión de fuego!
***¡Reclama la Espada de Jade y pasa a la próxima ronda del torneo!',RANGOS_VA(RANGO(6,14)),19.98,215,RESUMEN(13,23,10,IDIOMAS_VA('INGLES','ESPAÑOL','ALEMÁN'),'¡Lucha por la Espada de Jade en el Enfrentamiento en el Dojo, de LEGO® NINJAGO™! Cuenta con trampilla, prisión de fuego, dardos con punta envenenada, robot con espadas giratorias y 4 minifiguras.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_70756_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_70756_2.png'))),TO_DATE('01-JAN-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('EDIFICIOS'));
INSERT INTO PRODUCTO VALUES(70747,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Destructor de Roca','Han encerrado a Cole en las cuevas de la isla durante el Torneo de los Elementos. Colócalo en la cabina del Destructor de Roca, sujeta el mango retráctil para despegar y huye a toda velocidad. Cole necesitará usar todos sus poderes elementales para derrotar a Zugu y Sleven, que están armados y preparados para luchar. ¡Gira la rueda para disparar el poderoso cañón rápido automático NINJAGO™ de 8 misiles y haz pedazos su puesto de ataque Anacondrai! Incluye 3 minifiguras con diferentes armas: Cole, Zugu y Sleven.

***El Destructor de Roca cuenta con cañón rápido automático NINJAGO™ de 8 misiles, cabina abatible, mecanismo giratorio, alas ajustables, soportes para las armas de Cole y detalles creados con espadas ninja doradas.
***Armas incluidas: 2 espadas dentadas de Cole, espada Anacondrai de Zugu y daga de Sleven.
***¡Destruye el puesto de ataque Anacondrai con el cañón rápido automático NINJAGO™ de 8 misiles!',RANGOS_VA(RANGO(7,14)),29.99,236,RESUMEN(8,20,28,IDIOMAS_VA('INGLES','ESPAÑOL','ALEMÁN'),'¡Ayuda a Cole a escapar de su prisión en el Destructor de Roca, de LEGO® NINJAGO™! Cuenta con cañón rápido automático NINJAGO de 8 misiles y mango retráctil.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_70747_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_70747_2.png'))),TO_DATE('01-JAN-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('VEHÍCULOS'));
INSERT INTO PRODUCTO VALUES(851352,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Llavero de Zane: ninja de titanio','¡Deja que el héroe ninja Zane te proteja dondequiera que vayas! Unido a una auténtica minifigura de Zane, el ninja de titanio, este útil llavero se engancha fácilmente a tus llaves o tu mochila.

***Cuenta con una auténtica minifigura de Zane, el ninja de titanio, unida a una resistente anilla con cadena metálica.
***Úsalo como llavero o como amuleto para tu mochila.
***La minifigura no se puede separar de la cadena metálica.
***Un fantástico regalo para fans de los sets de juego LEGO® NINJAGO™.',RANGOS_VA(RANGO(6,99)),5.99,1,RESUMEN(6,3,2,IDIOMAS_VA('INGLES','ESPAÑOL'),'¡Demuestra el estilo ninja con el Llavero de Zane: ninja de titanio, de LEGO® NINJAGO™! Cuenta con una auténtica minifigura unida a una resistente anilla con cadena metálica.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_851352_1.png'))),TO_DATE('01-MAR-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('LLAVEROS'));
INSERT INTO PRODUCTO VALUES(70600,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Persecución en la moto ninja','Apunta al planeador del pirata del cielo con los cañones secretos de la moto de Kai. Esquiva las bombas del planeador y dispara con el cañón elemental del agua desde la asombrosa moto de Nya. Haz caer el planeador y despliega las espadas ninja doradas de la moto de Kai para atacar.

***Incluye 3 minifiguras con diferentes armas: Kai, Nya y Sqiffy.
***La moto de Kai cuenta con grandes ruedas de caucho, espadas ninja doradas que se despliegan y 2 cañones/propulsores secretos.
***La moto de Nya está armada con un cañón elemental del agua ajustable para disparar al pirata del cielo y cuenta con ruedas de caucho, alerones traseros ajustables y detalles creados con espadas ninja doradas.
***El planeador pirata cuenta con punto de fijación para la minifigura de Sqiffy, alas articuladas y función de lanzamiento de bombas; incluye también 2 bombas con llamas traslúcidas.
***Armas incluidas: espada traslúcida de Djinn en color gris con “Cole atrapado” y espada pirata de Sqiffy.',RANGOS_VA(RANGO(7,14)),19.99,231,RESUMEN(26,19,5,IDIOMAS_VA('INGLES','ESPAÑOL'),'Derriba el planeador de Sqiffy con la moto de Kai, equipada con ruedas de caucho y espadas ninja doradas que se despliegan, y la moto de Nya, armada con un cañón elemental del agua.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_70600_1.png')),IMAGEN('1',IMPORTAR_BINARIO('PROD_70600_2.png'))),TO_DATE('01-JAN-16','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('VEHÍCULOS'));
INSERT INTO PRODUCTO VALUES(851342,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Set de construcción de ejércitos','Suma guerreros a tus ejércitos ninja y fantasma con el asombroso Set de construcción de ejércitos LEGO® NINJAGO™. ¡Elige entre las fantásticas armas y da comienzo a la batalla! Incluye 4 minifiguras con diferentes armas: Kai, Jay, Wooo y Howla.

***Incluye 4 minifiguras con diferentes armas: Kai, Jay, Wooo y Howla.
***¡Construye tus ejércitos ninja y fantasma!
***¡Elige tus armas y prepárate para la batalla!
***Combínalo con los sets LEGO® NINJAGO™ para disfrutar de aún más opciones de juego.',RANGOS_VA(RANGO(6,99)),14.99,37,RESUMEN(20,12,4,IDIOMAS_VA('INGLES','ALEMÁN','FRANCÉS','ESPAÑOL'),'¡Construye tus ejércitos ninja y fantasma con el Set de construcción de ejércitos LEGO® NINJAGO™! Incluye 4 minifiguras y numerosas armas.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_851342_1.png'))),TO_DATE('01-SEP-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('MINIFIGURAS'));
