INSERT INTO FABRICA VALUES (SQ_FABRICA_ID.NEXTVAL,(select EC_ID from estado_ciudad where ec_tipo = 'CIUDAD' AND EC_NOMBRE = 'COPENHAGEN'),'FABRICA LEGO',DIRECCION('AASTVEJ 1','DK-7190',NULL,'local',telefonos_va(telefono(45,79,506070,'OFICINA'))));
INSERT INTO FABRICA VALUES (SQ_FABRICA_ID.NEXTVAL,(select EC_ID from estado_ciudad where ec_tipo = 'CIUDAD' AND EC_NOMBRE = 'CHESSY'),'FABRICA LEGO',NULL);
INSERT INTO FABRICA VALUES (SQ_FABRICA_ID.NEXTVAL,3,'FABRICA LEGO',NULL);
INSERT INTO FABRICA VALUES (SQ_FABRICA_ID.NEXTVAL,4,'FABRICA LEGO',NULL);
INSERT INTO FABRICA VALUES (SQ_FABRICA_ID.NEXTVAL,5,'FABRICA LEGO',NULL);
