INSERT INTO PRODUCTO VALUES(5005117,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Minifigura despertador de Jay','Deja que la Minifigura Despertador de Jay de LEGO® NINJAGO te proteja mientras duermes, y despiertes listo para tus aventuras diarias. Mira la hora en la pantalla LCD fácil de leer, mueve los brazos, muñecas y piernas de la minifigura jumbo de Jay y presiona su cabeza para activar el silenciador y la luz de fondo. El regalo ideal para los fans de sets LEGO NINJAGO.',RANGOS_VA(RANGO(6,99)),29.99,1,RESUMEN(23,12,9,IDIOMAS_VA('INGLES','ESPAÑOL'),'Levántate para las batallas ninja con esta Minifigura Despertador de Jay que incluye una minifigura jumbo movible, pantalla LCD, y funciones de silenciar y luz de fondo.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_5005117_1.png'))),TO_DATE('19-MAY-16','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('NUEVOS','MINIFIGURAS'));
INSERT INTO PRODUCTO VALUES(70751,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Templo de Airjitzu','¡Disfruta de la experiencia de construcción LEGO® NINJAGO definitiva con el majestuoso Templo de Airjitzu y el poblado de alrededor! El asombroso templo posee numerosos detalles arquitectónicos. La elaborada estructura de las paredes de la herrería cercana y los suaves tejados en curva del mercado de contrabando pondrán también a prueba tus habilidades de construcción con LEGO. ¡Apaga entonces las luces de tu habitación para ver el teatro de sombras giratorio en el templo!

***Incluye 12 minifiguras con diferentes armas: Lloyd, Kai, Jay, Zane, Cole, Nya, Wu, Misako, Dareth, cartero, Jesper y Claire.
***Armas incluidas: katanas para Lloyd, Kai, Jay, Zane, Cole y Nya.
***¡Busca los cofres escondidos en el mercado de contrabando!
***¡Prepara un espectáculo para tus amigos con el teatro de sombras giratorio!
***Recrea tus escenas favoritas de la serie de televisión NINJAGO: Maestros del Spinjitzu.',RANGOS_VA(RANGO(14,99)),199.99,2028,RESUMEN(42,52,35,IDIOMAS_VA('INGLES','ESPAÑOL'),'¡Construye el majestuoso Templo de Airjitzu! Cuenta con teatro de sombras giratorio con ladrillo luminoso, herrería y mercado de contrabando.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_70751_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_70751_2.png'))),TO_DATE('02-SEP-15','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('DIFICILES DE ENCONTRAR','EDIFICIOS','EXCLUSIVOS'));


INSERT INTO PRODUCTO VALUES(851345,(SELECT CL_ID FROM CLASIFICACION WHERE CL_NOMBRE = 'NINJAGO'),'Tapete de juego','¡Pon en marcha las aventuras más emocionantes con el Tapete de juego LEGOÂ® NINJAGOâ„¢! Este tapete de cartÃ³n plastificado impreso a doble cara cuenta con diferentes paisajes inspirados en el mundo de NINJAGO por cada lado. ¡Reúne tus sets LEGO NINJAGO favoritos y prepárate para escenificar asombrosas batallas!

***Tapete de juego de cartÃ³n plastificado impreso a doble cara con diferentes paisajes inspirados en el mundo de NINJAGOâ„¢ por cada lado.
***¡Planifica tu propia ruta a través de NINJAGO!
***Combínalo con los sets LEGO® NINJAGO para disfrutar de aún más opciones de juego.',RANGOS_VA(RANGO(6,99)),7.48,1,RESUMEN(100,63,1,IDIOMAS_VA('INGLES','ESPAÑOL'),'¡Sumérgete en una aventura ninja con el Tapete de juego LEGO® NINJAGO! Plastificado e impreso a doble cara, cuenta con asombrosos paisajes inspirados en el mundo de NINJAGO.'),IMAGENES_NT(IMAGEN('1',IMPORTAR_BINARIO('PROD_851345_1.png')),IMAGEN('2',IMPORTAR_BINARIO('PROD_851345_2.png'))),TO_DATE('01-JUN-12','DD-MON-RR'),EMPTY_BLOB(),CATEGORIAS_VA('HOME'));
