INSERT INTO LINEA_PROD VALUES (1,SQ_LINEA_PROD_ID.NEXTVAL,NULL);
INSERT INTO LINEA_PROD VALUES (1,SQ_LINEA_PROD_ID.NEXTVAL,NULL);
INSERT INTO LINEA_PROD VALUES (2,SQ_LINEA_PROD_ID.NEXTVAL,NULL);
INSERT INTO LINEA_PROD VALUES (3,SQ_LINEA_PROD_ID.NEXTVAL,NULL);
INSERT INTO LINEA_PROD VALUES (4,SQ_LINEA_PROD_ID.NEXTVAL,NULL);
INSERT INTO LINEA_PROD VALUES (5,SQ_LINEA_PROD_ID.NEXTVAL,NULL);