CREATE OR REPLACE PROCEDURE EXIST (V_NOMBRE VARCHAR2) IS  
  V_BFILE BFILE := BFILENAME('DIR_BINARIOS',V_NOMBRE);  
BEGIN
  DBMS_LOB.FILEOPEN(V_BFILE, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.FILECLOSE(V_BFILE);
  DBMS_OUTPUT.PUT_LINE('EL ARCHIVO EXISTE');  
  EXCEPTION WHEN OTHERS THEN    
    raise_application_error(-20100,'EL ARCHIVO NO EXISTE');
END;
/

CREATE OR REPLACE PROCEDURE INSERT_VAL_ONLINE(FAC NUMBER, FECHA IN DATE) IS
BEGIN
  insert into valoracion values (SQ_VALORACION_ID.NEXTVAL,FAC,NULL,FECHA,1,1,'F',NULL,'1');
END INSERT_VAL_ONLINE;
/
