/*-----	Métrica 1	-----*/
SELECT t.TI_ID "ID Tienda", ec.EC_NOMBRE "Ciudad", COUNT(ft.FT_CODIGO) "No. de Ventas", SUM(ft.FT_MONTO_USD)*1.1012 "Ganancia (EUR)" 
FROM TIENDA t, ESTADO_CIUDAD ec, FACTURA_TIENDA ft
WHERE ec.EC_ID = t.TI_FK_CIUDAD AND ft.FT_FK_TIENDA = t.TI_ID AND EXTRACT (YEAR FROM ft.FT_FECHA) = &ANNIO
GROUP BY t.TI_ID, ec.EC_NOMBRE
ORDER BY COUNT(ft.FT_CODIGO) DESC;