CREATE OR REPLACE PROCEDURE INSERTAR_FACTURA_TIENDA (
TIENDA IN FACTURA_TIENDA.FT_FK_TIENDA%TYPE,
CLIENTE IN FACTURA_TIENDA.FT_FK_CLIENTE%TYPE,
FECHA IN FACTURA_TIENDA.FT_FECHA%TYPE,
MONTO IN FACTURA_TIENDA.FT_MONTO_USD%TYPE
) IS
BEGIN
  INSERT INTO FACTURA_TIENDA VALUES (TIENDA,CLIENTE,SQ_FACTURA_TIENDA_ID.NEXTVAL,FECHA,MONTO);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_DETALLE_FACTURA(
FACT_T IN DETALLE_FACTURA.DF_FK_FACT_T%TYPE,
CLIENTE IN DETALLE_FACTURA.DF_FK_CLIENTE%TYPE,
PEDIDO IN DETALLE_FACTURA.DF_FK_PEDIDO%TYPE,
DET_PED IN DETALLE_FACTURA.DF_FK_DETPED%TYPE
)IS
BEGIN
  INSERT INTO DETALLE_FACTURA VALUES (SQ_DETALLE_FACTURA_ID.NEXTVAL,FACT_T,CLIENTE,PEDIDO,DET_PED);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_DETALLE_PEDIDO(
PEDIDO IN DETALLE_PEDIDO.DP_FK_PEDIDO%TYPE,
PAIS IN DETALLE_PEDIDO.DP_FK_PAIS%TYPE,
PRODUCTO IN DETALLE_PEDIDO.DP_FK_PRODUCTO%TYPE,
CANTIDAD IN DETALLE_PEDIDO.DP_CANTIDAD%TYPE,
SUBTOTAL IN DETALLE_PEDIDO.DP_SUBTOTAL%TYPE
)IS
BEGIN
  INSERT INTO DETALLE_PEDIDO VALUES (SQ_DETALLE_PEDIDO_ID.NEXTVAL,PEDIDO,PAIS,PRODUCTO,CANTIDAD,SUBTOTAL);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_DET_LOTE(
PLOTE IN DET_LOTE.DL_FK_PROD_LOTE%TYPE,
PEDIDO IN DET_LOTE.DL_FK_PEDIDO%TYPE,
DETPED IN DET_LOTE.DL_FK_DET_PEDIDO%TYPE,
CANTIDAD IN DET_LOTE.DL_CANTIDAD%TYPE
)IS
BEGIN
  INSERT INTO DET_LOTE VALUES (PLOTE,PEDIDO,DETPED,CANTIDAD);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_DESCUENTO(
PLOTE IN DESCUENTO.DES_FK_PROD_LOTE%TYPE,
FECHA IN DESCUENTO.DES_FECHA%TYPE,
CANTIDAD IN DESCUENTO.DES_CANTIDAD%TYPE
)IS
BEGIN
  INSERT INTO DESCUENTO VALUES (SQ_DESCUENTO_ID.NEXTVAL,PLOTE,FECHA,CANTIDAD);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_INSTALACION(
CIUDAD IN VARCHAR2,
NOMBRE IN INSTALACION.INS_NOMBRE%TYPE,
TIPO IN INSTALACION.INS_TIPO%TYPE,
CALLE IN VARCHAR2,
NUMEROEDIF IN VARCHAR2,
POSTAL IN NUMBER,
LOCAL IN VARCHAR2
)IS
BEGIN
  insert into INSTALACION VALUES (SQ_INSTALACION_ID.NEXTVAL,(select EC_ID from estado_ciudad where ec_tipo = 'CIUDAD' AND EC_NOMBRE = CIUDAD)
  ,NOMBRE,TIPO,DIRECCION(CALLE,NUMEROEDIF,POSTAL,LOCAL,NULL));
END;
/

/*DETALLE_PEDIDO*/

/*FACTURA_TIENDA*/
exec INSERTAR_FACTURA_TIENDA(1,1,TO_DATE('04/01/2016','dd/mm/rrrr'),100);
exec INSERTAR_FACTURA_TIENDA(2,2,TO_DATE('11/02/2016','dd/mm/rrrr'),200);
exec INSERTAR_FACTURA_TIENDA(3,3,TO_DATE('25/03/2016','dd/mm/rrrr'),300);
exec INSERTAR_FACTURA_TIENDA(4,4,TO_DATE('05/01/2015','dd/mm/rrrr'),400);
exec INSERTAR_FACTURA_TIENDA(5,5,TO_DATE('12/02/2015','dd/mm/rrrr'),500);
exec INSERTAR_FACTURA_TIENDA(6,6,TO_DATE('26/03/2015','dd/mm/rrrr'),100);
exec INSERTAR_FACTURA_TIENDA(7,7,TO_DATE('06/01/2014','dd/mm/rrrr'),200);
exec INSERTAR_FACTURA_TIENDA(8,8,TO_DATE('13/02/2014','dd/mm/rrrr'),700);
exec INSERTAR_FACTURA_TIENDA(9,9,TO_DATE('27/03/2014','dd/mm/rrrr'),500);
exec INSERTAR_FACTURA_TIENDA(10,10,TO_DATE('13/08/2013','dd/mm/rrrr'),200);

/*DETALLE_FACTURA*/
exec INSERTAR_DETALLE_FACTURA(1,1,1,1);
exec INSERTAR_DETALLE_FACTURA(2,2,2,2);
exec INSERTAR_DETALLE_FACTURA(3,3,3,3);
exec INSERTAR_DETALLE_FACTURA(4,4,4,4);
exec INSERTAR_DETALLE_FACTURA(5,5,5,5);
exec INSERTAR_DETALLE_FACTURA(6,6,6,6);
exec INSERTAR_DETALLE_FACTURA(7,7,7,7);
exec INSERTAR_DETALLE_FACTURA(8,8,8,8);
exec INSERTAR_DETALLE_FACTURA(9,9,9,9);
exec INSERTAR_DETALLE_FACTURA(10,10,10,10);
exec INSERTAR_DETALLE_FACTURA(1,1,1,11);
exec INSERTAR_DETALLE_FACTURA(2,2,2,12);
exec INSERTAR_DETALLE_FACTURA(3,3,3,13);
exec INSERTAR_DETALLE_FACTURA(4,4,4,14);
exec INSERTAR_DETALLE_FACTURA(5,5,5,15);
exec INSERTAR_DETALLE_FACTURA(6,6,6,16);
exec INSERTAR_DETALLE_FACTURA(7,7,7,17);
exec INSERTAR_DETALLE_FACTURA(8,8,8,18);
exec INSERTAR_DETALLE_FACTURA(9,9,9,19);
exec INSERTAR_DETALLE_FACTURA(10,10,10,20);

/*DET_LOTE*/


/*DESCUENTO*/


/*INSTALACION*/
EXEC INSERTAR_INSTALACION('SAINT PETERSBURG','SERIOUS PLAY','IYD','1 DALI BLVD',NULL,33701,'LOCAL');
EXEC INSERTAR_INSTALACION('WINTER HAVEN','SERIOUS PLAY','PARQUE','1 LEGOLAND WAY',NULL,33884,'LOCAL');
