INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'UNITED STATES','AMERICAN','AMERICA',MONEDA('USD',1));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'GERMAN','GERMAN','EUROPE',MONEDA('EUR',1.11465));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'ENGLAND','ENGLISH','EUROPE',MONEDA('EUR',1.11465));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'CANADA','CANADIAN','AMERICA',MONEDA('CAD',0.763097));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'AUSTRIA','AUSTRALIAN','OCEANIA',MONEDA('AUD',0.72259));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'BELGIUM','BELGIAN','EUROPE',MONEDA('EUR',1.11465));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'DENMARK','DANISH','EUROPE',MONEDA('EUR',1.11465));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'FRANCE','FRENCH','EUROPE',MONEDA('EUR',1.11465));
INSERT INTO PAIS VALUES (SQ_PAIS_ID.NEXTVAL,'SWEDEN','SWEDISH','EUROPE',MONEDA('EUR',1.11465));
