CREATE DIRECTORY DIR_BINARIOS AS 'C:\oraclexe\Binarios';
--Cambiar a donde quieran guardar

CREATE OR REPLACE FUNCTION IMPORTAR_BINARIO(NOMBRE VARCHAR2)
RETURN BLOB IS
	R_BLOB BLOB;
	V_BFILE BFILE := BFILENAME('DIR_BINARIOS',NOMBRE);
BEGIN
	DBMS_LOB.CREATETEMPORARY(R_BLOB,true);
	DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);
	DBMS_LOB.LOADFROMFILE(R_BLOB,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
	DBMS_LOB.CLOSE(V_BFILE);
	RETURN R_BLOB;
END;


/*

INSERT INTO CLASIFICACION(CL_ID,CL_NOMBRE,CL_DESCRIPCION,CL_LICENCIA,CL_TIPO,CL_IMAGENES) VALUES(
  1,
  'ROBOTS',
  'ALGO',
  'S',
  'ASD',
  IMAGENES_NT(IMPORTAR_BINARIO('ER.png'),IMPORTAR_BINARIO('23687.jpg'))
);

*/
/*Dos imágenes de prueba