-- TODAVIA NO SE COMO HACER EL COUNT PARA EL CLIENTE QUE ESTA COMPRANDO,
-- DADO QUE CREO QUE LO HACE PARA TODOS LOS CLIENTES
Create or replace trigger maximo_compraonline
after insert on DETALLE
FOR EACH ROW 
DECLARE
CANT_DISPONIBLE NUMBER;
CANT_COMPRA NUMBER; 							
BEGIN
SELECT D.DIP_LIMITE into CANT_DISPONIBLE FROM DISP_PROD D 
WHERE D.DIP_FK_PAIS = :NEW.DET_FK_PAIS AND D.DIP_FK_PRODUCTO = :NEW.DET_FK_PRODUCTO;

SELECT COUNT(*) into CANT_COMPRA FROM DETALLE D , FACTURA_ONLINE F  
WHERE D.DET_FK_FACT_ONLI = F.FO_NUMERO;
-- COMPARAR CON CLIENTE
IF CANT_COMPRA > CANT_DISPONIBLE THEN
RAISE_APPLICATION_ERROR(-20123,'EXCEDE EL LIMITE DE COMPRA POR PAIS');
END IF;
END;