CREATE OR REPLACE TRIGGER CH_DIRECCION
BEFORE INSERT OR UPDATE OF TI_DIRECCION ON TIENDA
FOR EACH ROW
DECLARE  
  CURSOR TELEFONOS IS SELECT TREAT(:NEW.TI_DIRECCION as DIRECCION).DI_TELEFONOS FROM TIENDA;
  RESULTADO TELEFONOS%ROWTYPE;
BEGIN
  IF :NEW.TI_DIRECCION IS NULL THEN
    RAISE_APPLICATION_ERROR(-20003, 'LA DIRECCION NO PUEDE SER ESTAR VACIA');
  ELSE
    IF RESULTADO.telefonos_va(1).TELE_TIPO <> 'LOCAL' THEN
      RAISE_APPLICACION_ERROR(-20005,/*'EL TIPO DE TELEFONO NO ES VALIDO'*/RESULTADO.telefonos_va(1).TELE_TIPO);
    END IF;
  END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20005,'HA OCURRIDO UN ERROR');
END;
/
drop trigger CH_direccion;/**/