CREATE OR REPLACE TRIGGER CH_DIRECCION
BEFORE INSERT OR UPDATE ON TIENDA
FOR EACH ROW
DECLARE
  TI_DIRECCION TIENDA.TI_DIRECCION%TYPE;
  CURSOR TELEFONOS IS SELECT TREAT(TI_DIRECCION as DIRECCION).DI_TELEFONOS FROM TIENDA;
  RESULTADO TELEFONOS%ROWTYPE;
BEGIN
  IF TI_DIRECCION IS NULL THEN
    RAISE_APPLICATION_ERROR(-20003, 'LA DIRECCION NO PUEDE SER ESTAR VACIA');
  ELSE
    IF RESULTADO.telefonos_va(1).TELE_TIPO <> 'LOCAL' THEN
      RAISE_APPLICACION_ERROR(-20005,'EL TIPO DE TELEFONO NO ES VALIDO');
    END IF;
  END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20005,'HA OCURRIDO UN ERROR');
END;
/
drop trigger CH_direccion;/**/